# spring.jpa.properties.hibernate.dialect: org.hibernate.dialect.MySQLDialect

# If you want to enable the AWS RDS configuration, uncomment the following block
# spring:
#   datasource:
#     url: jdbc:mysql://bank-app.cnfidgvpmn0q.us-west-1.rds.amazonaws.com:3306/bank_app
#     username: root
#     password: Alasho514real
#     driver-class-name: com.mysql.cj.jdbc.Driver
#   jpa:
#     hibernate:
#       ddl-auto: update
#server.port: 5000
#jwt
#app:
#  jwt-secret: aPC3kbPI5uQggGVJqMPxmivLFFanDhBVXbMWM/dbMik=
#  jwt-expiration: 86400000
jwt-info:
  app:
    jwt-secret: aPC3kbPI5uQggGVJqMPxmivLFFanDhBVXbMWM/dbMik=
    jwt-expiration:
      milliseconds: 86400000

spring:
    datasource:
      url: jdbc:mysql://bank-app.cnfidgvpmn0q.us-west-1.rds.amazonaws.com:3306/eventease?useSSL=false&serverTimezone=UTC
      username: root
      password: 'Alasho514real'
      driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
      hibernate:
        ddl-auto: update

    mail:
      host: smtp.gmail.com
      port: 465
      username: oyinlolaalasoluyi@gmail.com
      password: oqpwexwrfmcadalp
      properties:
        mail:
          smtp:
            auth: true
            starttls.enable: true
            smtp.ssl.enable: true
    profiles:
      active: spring.profiles.active
      flyway:
        baseline-on-migrate: true
        enabled: true
        user: root
        password: Alasho514real
        baseline-description: init
        baseline-version: 1
        clean-disabled: false
        ignore-migration-patterns: missing*:pending
security:
  user:
    name: oyin
    password: 12345

TWILIO_ACCOUNT_SID: ACdd9f621c85c78bfb8b95b18ad7a3979c
TWILIO_AUTH_TOKEN: cd9d72a69945d497bb087b0c9b59a1ac
TWILIO_OUTGOING_SMS_NUMBER: '+13612644939'

server:
  port: 5000